services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:7788:3000"
    restart: always
    volumes:
      - type: volume
        source: payroll-data
        target: /app/data

volumes:
  payroll-data:
