import type { Metadata } from "next";
import "./globals.css";
import AppLayout from "@/components/app-layout";


export const metadata: Metadata = {
  title: "工资工作台",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
